baseurl = "http://angrygopher.com"
title = "AngryGopher"
theme = "vec"
languageCode = "en-us"
paginate = 15

# Enable comments by entering your Disqus shortname
#disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-89451106-1"

[params]
  Keywords = "golang, programming"
  Description = "Examples, articles, tips and tricks about Go programming language."
  
  Avater = "img/AngryGopher.png"
  SelfIntro = "Examples, articles, tips and tricks about Go programming language." 
  #Email = "you@example.com"
  
  GithubID = "angrygopher"
  #TwitterID = "Your Twitter ID"
  #FacebookID = "Your Facebook ID"
  #LinkedInID = "Your LinkedIn ID"
  #GoogleplusID = "Your Googleplus ID"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.about]]
    name = "about"
    weight = 1
    url = "/about"
    
