baseurl = "http://angrygopher.com"
title = "Angry Gopher"
theme = "vec"
languageCode = "en-us"
paginate = 15

# Enable comments by entering your Disqus shortname
#disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
#googleAnalytics = "Your Google Analytics tracking code"

[params]
  Keywords = "golang, programming"
  Description = "Examples, articles, tips and tricks about Go programming language."
  
  Avater = "img/AngryGopher.png"
  SelfIntro = "Examples, articles, tips and tricks about Go programming language." 
  #Email = "you@example.com"
  
  #GithubID = "Your Github ID"
  #TwitterID = "Your Twitter ID"
  #FacebookID = "Your Facebook ID"
  #LinkedInID = "Your LinkedIn ID"
  #GoogleplusID = "Your Googleplus ID"